### ISSUE TITLE
Can't get this plugin to work

### ISSUE THREAD

**Issue by silouanwright** [guillermooo/Vintageous_Plugin_Surround#10]
Mac OS X Yosimite, ST3. Put in Installed Packages, listed it in Package Control.What other information should I include?

**Comment by danrasmuson** [comment]
I'm wondering this same thing. Would really love to use this plugin.

**Comment by guillermooo** [comment]
This a plugin for the Sublime Text Vintageous plugin. Vintageous needs to be installed too.

**Comment by silouanwright** [comment]
quite a conclusion you jumped to... vintageous is definitely installed

**Comment by guillermooo** [comment]
@rey-wright Thanks for the additional info. It would have been best to provide it in the first report. Otherwise I'm forced to jump to conclusions. These are my assumptions now:
- you have Vintageous installed
- you installed this plugin manually using the download link (putting .sublime-package under Installed Packages)

If so, it seems the published .sublime-package was old. I've updated it now.
