### ISSUE TITLE
cs for word objects?

### ISSUE THREAD

**Issue by wavded** [guillermooo/Vintageous_Plugin_Surround#9]
e.g. given

```
hi
```

and running `csw"` in vim-surround, I'd get:

```
"hi"
```

**Comment by ghost** [comment]
did you try `ciw`

**Comment by wavded** [comment]
`ciw` deletes the word and puts me in insert mode.

**Comment by jordwalke** [comment]
:+1:  Noticed this too.

**Comment by rahiyer** [comment]
To add new surrounding quotes `ysiw"` works for me. 

`cs` changes existing surrounding. Example: 

` 'hi' ` can be changed to `"hi"` using `cs'"`

**Comment by vvmk** [comment]
These comments are hella old but I feel compelled to leave this here: 
`w` is a motion to the next beginning of a word.
`aw` is a text object (a word) including the word and its surrounding whitespace
`iw` is a text object (inner word) that includes just the word (no whitespace)
therefore `ciw` is change inner word. 

The original plugin is designed so that `cs[current surround][new surround]` switches the current surround character with a different one, thus it assumes you don't need to use a text object. Adding them where there are none is done with `ys` .
(source: vim-surround README)

This is all working fine for me.

I'm here because finding this package just now made me smile (almost as much as Mr. Pope's plugin) and I wanted to say thanks!
